apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: project
data: 
  DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: project
  labels: 
    app: backend
    tier: backend
    project: project
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: backend
      tier: backend
      project: project
  template:
  metadata:
    labels:
      app: backend
      tier: backend
      project: project
  spec:
    containers:
    - name: nginx
      image: joindevops/backend:1.0.0  ### srikanth9959/deployment:1.0.0
      envForm:
      - ConfigMapRef:
          name: backend
---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: project
spec:
  type: LoadBalancer
  selector: # labels will used here for selecting the pod
    app: backend
    tier: backend
    project: project
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080