# Headless Service for StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: project
  labels:
    app: mysql
    project: project
    tier: db
spec:
  clusterIP: None  # Important for headless service, no IP will be assigned to the service
  selector:
    app: mysql
    project: project
    tier: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
# Normal Service
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: project
  labels:
    app: mysql
    project: project
    tier: db
spec:
  selector: # labels will be used here for selecting the pod
    app: mysql
    project: project
    tier: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
# StatefulSet for MySQL
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: project  
spec:
  selector:
    matchLabels:
      app: mysql
      project: project
      tier: db      
  serviceName: "mysql-headless" # This should reference the headless service
  replicas: 2 # Number of MySQL replicas
  minReadySeconds: 10 # Time to wait before considering the pod ready
  template:
    metadata:
      labels:
        app: mysql # Must match .spec.selector.matchLabels
        project: project
        tier: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: joindevops/mysql:1.0.0
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql
      namespace: project
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc" # Ensure this StorageClass exists in your cluster
      resources:
        requests:
          storage: 1Gi
